version: '3.5'

services:
  postgres:
    container_name: postgres
    image: postgres
    command: postgres -c logging_collector=on -c log_destination=stderr -c log_directory=/logs    
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
      PGUSER: postgres
    volumes:
       - ./data:/data/postgres
       - ./logs:/logs
       - ./backups:/backups
    ports:
      - "5432:5432"
    restart: unless-stopped
  
  python_server:
    container_name: python_server
    image: python
    command: python -m http.server
    working_dir: /app
    volumes:
       - ./logs:/app/logs
       - ./backups:/app/backups    
    ports:
      - "8000:8000"
